### ISSUE TITLE
Doesn't work in production mode

### ISSUE THREAD

**Issue by ThomsCass** [Lendix/bankin#2]
Hey, When I want to connect to an item even if i don't provide an redirect URL I got :

`Optional redirect URL that temporarily overrides the application's redirect URL. Only usable for sandbox applications`

Thanks

**Comment by PierrickP** [comment]
Hi,
Sorry we don't use in production yet.
Can you try to replace `items.connectUrl` (file `dist/user.js`) method per 

```JavaScript
      connectUrl: function connectUrl(bank_id, redirect_url) {
        var query = {
          client_id: _this._client.clientId,
          access_token: _this.access_token,
          bank_id: bank_id
        };

        if (redirect_url) {
          query.redirect_url = redirect_url;
        }

        return Promise.resolve(_url2.default.format({
          query: query,
          pathname: _this._client.endpoint + '/items/connect'
        }));
      },
```

Thanks
